version: '3'

services:
  iris:
    build: .
    image: iris:1.0
    container_name: iris
    environment:
      - REDIS_HOST=redis
    ports:
      - 5000:5000
    extra_hosts:
        - "app-redis:127.0.0.1"
    command: /usr/src/app/start.sh
